/**
 * Oracle Hook IPC protocol — shared contract between HexCore's emulation worker
 * and the Pythia agent.
 *
 * Transport: SharedArrayBuffer (Project Perseus zero-copy channel) OR stdio
 * NDJSON frames, depending on attach mode. Payload schema is identical across
 * transports.
 *
 * Direction conventions:
 *   HexCore -> Pythia   ::  DecisionRequest
 *   Pythia  -> HexCore  ::  DecisionResponse
 *   Pythia  -> HexCore  ::  ToolCall (inspection tools, no state change)
 *   HexCore -> Pythia   ::  ToolResult (response to ToolCall)
 *
 * eventId is an opaque string generated by HexCore and echoed by Pythia so
 * request/response pairs can be matched when multiple hooks fire in quick
 * succession.
 */

import { z } from "zod";

// ═══════════════════════════════════════════════════════════════════════════
// Trigger definitions — what HexCore is configured to pause on.
// ═══════════════════════════════════════════════════════════════════════════

export const TriggerKind = z.enum([
  "instruction",       // fire on specific PC
  "api",               // fire on resolved API call
  "memory_read",       // fire on read from region
  "memory_write",      // fire on write to region
  "exception",         // fire on emulator exception (segfault, div/0, ...)
  "timing_check",      // heuristic: fire after QPC/KUSER/GetTickCount read
  "peb_access",        // heuristic: fire on gs:[60]/fs:[30] PEB read
]);
export type TriggerKind = z.infer<typeof TriggerKind>;

export const TriggerSchema = z.object({
  kind: TriggerKind,
  value: z.string(),           // address (hex), API name, region "base-limit"
  reason: z.string(),          // human-readable why this fired
});
export type Trigger = z.infer<typeof TriggerSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Machine context — what Pythia sees when execution pauses.
// ═══════════════════════════════════════════════════════════════════════════

export const RegisterStateSchema = z.object({
  // x86_64 GPRs + RIP + RFLAGS. All hex strings prefixed 0x.
  rax: z.string(), rbx: z.string(), rcx: z.string(), rdx: z.string(),
  rsi: z.string(), rdi: z.string(), rbp: z.string(), rsp: z.string(),
  r8:  z.string(), r9:  z.string(), r10: z.string(), r11: z.string(),
  r12: z.string(), r13: z.string(), r14: z.string(), r15: z.string(),
  rip: z.string(), rflags: z.string(),
  // Segment bases that matter for anti-debug (gs = PEB on x64).
  gs_base: z.string().optional(),
  fs_base: z.string().optional(),
});
export type RegisterState = z.infer<typeof RegisterStateSchema>;

export const DisasmLineSchema = z.object({
  address: z.string(),         // 0x-prefixed hex
  bytes:   z.string(),         // hex string, no separators
  mnemonic: z.string(),
  operands: z.string(),
});
export type DisasmLine = z.infer<typeof DisasmLineSchema>;

export const CallFrameSchema = z.object({
  address: z.string(),
  symbol:  z.string().optional(),
  module:  z.string().optional(),
});
export type CallFrame = z.infer<typeof CallFrameSchema>;

export const MemoryWindowSchema = z.object({
  base:  z.string(),           // starting address
  bytes: z.string(),           // hex, contiguous dump
});
export type MemoryWindow = z.infer<typeof MemoryWindowSchema>;

export const SessionStateSchema = z.object({
  sessionId: z.string(),
  instructionsExecuted: z.number().int().nonnegative(),
  apisCalled: z.array(z.string()),         // last N API names
  elapsedMs: z.number().nonnegative(),
  pauseCount: z.number().int().nonnegative(), // how many times we've paused
});
export type SessionState = z.infer<typeof SessionStateSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Decision Request — HexCore asks, Pythia decides.
// ═══════════════════════════════════════════════════════════════════════════

export const DecisionRequestSchema = z.object({
  kind: z.literal("decision_request"),
  eventId: z.string(),
  trigger: TriggerSchema,
  context: z.object({
    registers: RegisterStateSchema,
    disassembly: z.array(DisasmLineSchema),   // ~16 lines around RIP
    callStack: z.array(CallFrameSchema),
    memoryWindow: MemoryWindowSchema,         // ±64 bytes around RIP or operand
  }),
  session: SessionStateSchema,
});
export type DecisionRequest = z.infer<typeof DecisionRequestSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Decision Response — Pythia's verdict.
// ═══════════════════════════════════════════════════════════════════════════

export const PatchTarget = z.enum(["register", "memory", "flag"]);
export type PatchTarget = z.infer<typeof PatchTarget>;

export const PatchSchema = z.object({
  target: PatchTarget,
  location: z.string(),         // register name (rax..r15), address (hex), or flag (zf, cf, ...)
  value: z.string(),            // hex or decimal
  size: z.number().int().positive().optional(),  // bytes for memory patches
});
export type Patch = z.infer<typeof PatchSchema>;

export const SkipSchema = z.object({
  instructions: z.number().int().positive().optional(),
  untilAddress: z.string().optional(),   // hex, skip until PC hits this
});
export type Skip = z.infer<typeof SkipSchema>;

export const DecisionActionSchema = z.enum([
  "continue",        // resume emulation unchanged
  "patch",           // apply patch, then resume
  "skip",            // skip N instructions or until address
  "patch_and_skip",  // patch then skip
  "abort",           // terminate emulation (sample deemed too dangerous / stuck)
]);
export type DecisionAction = z.infer<typeof DecisionActionSchema>;

export const DecisionResponseSchema = z.object({
  kind: z.literal("decision_response"),
  eventId: z.string(),                     // must match request
  action: DecisionActionSchema,
  patches: z.array(PatchSchema).optional(),
  skip: SkipSchema.optional(),
  reasoning: z.string().optional(),        // one short line, for trace logs
  modelUsed: z.enum(["haiku", "sonnet", "opus"]).optional(),
  costUsd: z.number().nonnegative().optional(),
});
export type DecisionResponse = z.infer<typeof DecisionResponseSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Inspection tool calls — Pythia asks HexCore for more context before deciding.
// These do NOT resume emulation; execution stays paused until a DecisionResponse.
// ═══════════════════════════════════════════════════════════════════════════

export const ToolCallSchema = z.discriminatedUnion("tool", [
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("read_memory"),
    args: z.object({ address: z.string(), length: z.number().int().positive().max(4096) }),
  }),
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("disassemble"),
    args: z.object({ address: z.string(), count: z.number().int().positive().max(64) }),
  }),
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("query_helix"),
    args: z.object({ functionAddress: z.string() }),
  }),
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("search_hql"),
    args: z.object({ pattern: z.string() }),
  }),
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("list_strings_near"),
    args: z.object({ address: z.string(), radius: z.number().int().positive().default(256) }),
  }),
  z.object({
    kind: z.literal("tool_call"),
    eventId: z.string(),
    callId: z.string(),
    tool: z.literal("get_imports"),
    args: z.object({}),
  }),
]);
export type ToolCall = z.infer<typeof ToolCallSchema>;

export const ToolResultSchema = z.object({
  kind: z.literal("tool_result"),
  eventId: z.string(),
  callId: z.string(),
  ok: z.boolean(),
  data: z.unknown(),           // tool-specific; validated by tool-specific parsers
  error: z.string().optional(),
});
export type ToolResult = z.infer<typeof ToolResultSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Session lifecycle — handshake + teardown.
// ═══════════════════════════════════════════════════════════════════════════

export const HandshakeSchema = z.object({
  kind: z.literal("handshake"),
  protocolVersion: z.literal(1),
  hexcoreVersion: z.string(),
  pythiaVersion: z.string(),
  capabilities: z.array(z.string()),   // e.g. ["read_memory", "query_helix"]
});
export type Handshake = z.infer<typeof HandshakeSchema>;

export const SessionEndSchema = z.object({
  kind: z.literal("session_end"),
  sessionId: z.string(),
  reason: z.enum(["emulation_complete", "aborted", "timeout", "error"]),
  summary: z.object({
    instructionsExecuted: z.number().int().nonnegative(),
    pauseCount: z.number().int().nonnegative(),
    apisResolved: z.number().int().nonnegative(),
    patchesApplied: z.number().int().nonnegative(),
    totalCostUsd: z.number().nonnegative(),
    beaconUrls: z.array(z.string()).optional(),
    iocsExtracted: z.array(z.string()).optional(),
  }).optional(),
});
export type SessionEnd = z.infer<typeof SessionEndSchema>;

// ═══════════════════════════════════════════════════════════════════════════
// Top-level message envelope.
// ═══════════════════════════════════════════════════════════════════════════

export const OracleMessageSchema = z.discriminatedUnion("kind", [
  HandshakeSchema,
  DecisionRequestSchema,
  DecisionResponseSchema,
  ToolCallSchema,
  ToolResultSchema,
  SessionEndSchema,
]);
export type OracleMessage = z.infer<typeof OracleMessageSchema>;
